apiVersion: v1
kind: ConfigMap
metadata:
  name: cvs-cm-hook
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-30"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
{{ ( .Files.Glob "scripts/*" ).AsConfig | indent 2 }}