{{- if .Values.global.namespace }}
{{- if not (lookup "v1" "Namespace" "" .Values.global.namespace) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ default .Release.Namespace .Values.global.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-60"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
{{- end }}
{{- end }}